### PR TITLE
Use Delay monad for reduction instead of Fuel

### PR DESCRIPTION
**Pull request by jespercockx**
This can be merged as soon as https://github.com/agda/agda2hs/pull/263/ is merged upstream (cc @flupe)

### CODE REVIEW

**Comment by liesnikov** [comment]
I see the build is failing, probably because agda2hs dependency wasn't updated.

We can probably incorporate something like this action so that you don't have to spin up nix locally to do the update https://github.com/marketplace/actions/update-nix-flake-lock.

**Comment by jespercockx** [comment]
The upstream PR has been merged, @liesnikov could you (show how to) update the CI so it uses https://github.com/agda/agda2hs/commit/984821ab84b33917a1709c36bf66a0732ebbb46d?

**Comment by liesnikov** [comment]
You should run `nix flake update` to update all dependencies (agda2hs and scope sources in our case for now). Or `nix update agda2hs-src` (as seen in the inputs part of flake.nix file).

I'll push an update in a second to this branch because I can't get the action to run somehow.

**Comment by liesnikov** [comment]
Created a workflow, so from now on you can simply go to the Update flake action in the Actions tab (https://github.com/jespercockx/agda-core/actions/workflows/flake-lock-update.yml) and run it.
This will create a PR with updated dependencies.

**Pull request merged**
